name: Build and Release APK

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install Dependencies  
      run: npm install

    - name: Install Quasar CLI
      run: npm install -g @quasar/cli @quasar/icongenie
    
    - name: Set up zsh & jdk
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh openjdk-17-jdk
        
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
        
    - name: Setup Android SDK Tools
      # You may pin to the exact commit or the version.
      # uses: android-actions/setup-android@72fdd2e74f58fb338a2743720c0847b8becf1589
      uses: android-actions/setup-android@v2.0.2

    - name: Add Mode
      run: echo "org.flypen.app" | quasar mode add capacitor
      
    - name: Http
      run: jq 'del(.server)' ./src-capacitor/capacitor.config.json > ./src-capacitor/edit.json && mv ./src-capacitor/edit.json ./src-capacitor/capacitor.config.json
      
    - name: Build APK
      env: 
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
      run: quasar build -m capacitor -T android
      
    - name: Add Icon
      run: icongenie generate -m capacitor -i ./icon.png
      
    - name: Build APK with icon
      env: 
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
      run: quasar build -m capacitor -T android

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.AAA }}
        release_branches: main

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.AAA }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: true

    - name: Setup Android SDK Tools
      # You may pin to the exact commit or the version.
      # uses: android-actions/setup-android@72fdd2e74f58fb338a2743720c0847b8becf1589
      uses: android-actions/setup-android@v2.0.2

    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        zsh -c "echo $KEYSTORE_BASE64 | base64 -d > my-release-key.keystore"
  
    - name: Sign APK
      env:
        ALIAS: "org.flypen.app"
        KEYSTORE_PASSWORD: ${{ secrets.PASSWORD }}
        KEY_PASSWORD: ${{ secrets.PASSWORD }} 
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
      run: |
        wget https://dl.google.com/android/repository/build-tools_r34-linux.zip
        unzip build-tools_r34-linux.zip
        #./android-14/zipalign -v 4 ./dist/capacitor/android/apk/release/app-release-unsigned.apk signed.apk
        cp ./dist/capacitor/android/apk/release/app-release-unsigned.apk ./signed.apk
        echo $KEY_PASSWORD | ./android-14/apksigner sign --ks ./my-release-key.keystore --ks-key-alias org.flypen.app ./signed.apk
        
    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.AAA }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./signed.apk
        asset_name: app.apk
        asset_content_type: application/vnd.android.package-archive
